/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ErrorSeverity: typeof import('./src/utils/ERROR-HANDLER__GLOBAL--SYSTEM.js')['ErrorSeverity']
  const ErrorTypes: typeof import('./src/utils/ERROR-HANDLER__GLOBAL--SYSTEM.js')['ErrorTypes']
  const GlobalErrorHandler: typeof import('./src/utils/ERROR-HANDLER__GLOBAL--SYSTEM.js')['GlobalErrorHandler']
  const console.error: typeof import('console')['error']
  const console.log: typeof import('console')['log']
  const createDevPlugins: typeof import('./src/utils/PLUGINS__VITE--UNIFIED.js')['createDevPlugins']
  const createProdPlugins: typeof import('./src/utils/PLUGINS__VITE--UNIFIED.js')['createProdPlugins']
  const createTestPlugins: typeof import('./src/utils/PLUGINS__VITE--UNIFIED.js')['createTestPlugins']
  const createVitePlugins: typeof import('./src/utils/PLUGINS__VITE--UNIFIED.js')['createVitePlugins']
  const debugEnvironment: typeof import('./src/utils/ENV-PROCESSOR__VITE--WRAPPER.js')['debugEnvironment']
  const del: typeof import('./src/utils/HTTP-CLIENT__API--UNIFIED.js')['del']
  const download: typeof import('./src/utils/HTTP-CLIENT__API--UNIFIED.js')['download']
  const eNVPROCESSORVITEWRAPPER: typeof import('./src/utils/ENV-PROCESSOR__VITE--WRAPPER.js')['default']
  const eRRORHANDLERGLOBALSYSTEM: typeof import('./src/utils/ERROR-HANDLER__GLOBAL--SYSTEM.js')['default']
  const get: typeof import('./src/utils/HTTP-CLIENT__API--UNIFIED.js')['get']
  const getErrorStatistics: typeof import('./src/utils/ERROR-HANDLER__GLOBAL--SYSTEM.js')['getErrorStatistics']
  const getPluginInfo: typeof import('./src/utils/PLUGINS__VITE--UNIFIED.js')['getPluginInfo']
  const getToken: typeof import('./src/utils/HTTP-CLIENT__API--UNIFIED.js')['getToken']
  const globalErrorHandler: typeof import('./src/utils/ERROR-HANDLER__GLOBAL--SYSTEM.js')['globalErrorHandler']
  const hTTPCLIENTAPIUNIFIED: typeof import('./src/utils/HTTP-CLIENT__API--UNIFIED.js')['default']
  const handleError: typeof import('./src/utils/ERROR-HANDLER__GLOBAL--SYSTEM.js')['handleError']
  const ifNull: typeof import('./src/utils/HTTP-CLIENT__API--UNIFIED.js')['ifNull']
  const is: typeof import('./src/utils/HTTP-CLIENT__API--UNIFIED.js')['is']
  const isArray: typeof import('./src/utils/HTTP-CLIENT__API--UNIFIED.js')['isArray']
  const isAuthenticated: typeof import('./src/utils/HTTP-CLIENT__API--UNIFIED.js')['isAuthenticated']
  const isBoolean: typeof import('./src/utils/HTTP-CLIENT__API--UNIFIED.js')['isBoolean']
  const isClient: typeof import('./src/utils/HTTP-CLIENT__API--UNIFIED.js')['isClient']
  const isDate: typeof import('./src/utils/HTTP-CLIENT__API--UNIFIED.js')['isDate']
  const isDef: typeof import('./src/utils/HTTP-CLIENT__API--UNIFIED.js')['isDef']
  const isElement: typeof import('./src/utils/HTTP-CLIENT__API--UNIFIED.js')['isElement']
  const isEmpty: typeof import('./src/utils/HTTP-CLIENT__API--UNIFIED.js')['isEmpty']
  const isExternal: typeof import('./src/utils/HTTP-CLIENT__API--UNIFIED.js')['isExternal']
  const isFunction: typeof import('./src/utils/HTTP-CLIENT__API--UNIFIED.js')['isFunction']
  const isNull: typeof import('./src/utils/HTTP-CLIENT__API--UNIFIED.js')['isNull']
  const isNullOrUndef: typeof import('./src/utils/HTTP-CLIENT__API--UNIFIED.js')['isNullOrUndef']
  const isNullOrWhitespace: typeof import('./src/utils/HTTP-CLIENT__API--UNIFIED.js')['isNullOrWhitespace']
  const isNumber: typeof import('./src/utils/HTTP-CLIENT__API--UNIFIED.js')['isNumber']
  const isObject: typeof import('./src/utils/HTTP-CLIENT__API--UNIFIED.js')['isObject']
  const isPromise: typeof import('./src/utils/HTTP-CLIENT__API--UNIFIED.js')['isPromise']
  const isRegExp: typeof import('./src/utils/HTTP-CLIENT__API--UNIFIED.js')['isRegExp']
  const isServer: typeof import('./src/utils/HTTP-CLIENT__API--UNIFIED.js')['isServer']
  const isString: typeof import('./src/utils/HTTP-CLIENT__API--UNIFIED.js')['isString']
  const isUndef: typeof import('./src/utils/HTTP-CLIENT__API--UNIFIED.js')['isUndef']
  const isUrl: typeof import('./src/utils/HTTP-CLIENT__API--UNIFIED.js')['isUrl']
  const isWhitespace: typeof import('./src/utils/HTTP-CLIENT__API--UNIFIED.js')['isWhitespace']
  const isWindow: typeof import('./src/utils/HTTP-CLIENT__API--UNIFIED.js')['isWindow']
  const pLUGINSVITEUNIFIED: typeof import('./src/utils/PLUGINS__VITE--UNIFIED.js')['default']
  const patch: typeof import('./src/utils/HTTP-CLIENT__API--UNIFIED.js')['patch']
  const post: typeof import('./src/utils/HTTP-CLIENT__API--UNIFIED.js')['post']
  const put: typeof import('./src/utils/HTTP-CLIENT__API--UNIFIED.js')['put']
  const reLogIn: typeof import('./src/utils/HTTP-CLIENT__API--UNIFIED.js')['reLogIn']
  const removeToken: typeof import('./src/utils/HTTP-CLIENT__API--UNIFIED.js')['removeToken']
  const reportError: typeof import('./src/utils/ERROR-HANDLER__GLOBAL--SYSTEM.js')['reportError']
  const request: typeof import('./src/utils/HTTP-CLIENT__API--UNIFIED.js')['request']
  const runHttpClientDemo: typeof import('./src/utils/TEST__HTTP-CLIENT--DEMO.js')['runHttpClientDemo']
  const setToken: typeof import('./src/utils/HTTP-CLIENT__API--UNIFIED.js')['setToken']
  const showAlert: typeof import('./src/utils/HTTP-CLIENT__API--UNIFIED.js')['showAlert']
  const tESTHTTPCLIENTDEMO: typeof import('./src/utils/TEST__HTTP-CLIENT--DEMO.js')['default']
  const upload: typeof import('./src/utils/HTTP-CLIENT__API--UNIFIED.js')['upload']
  const validateEnvironment: typeof import('./src/utils/ENV-PROCESSOR__VITE--WRAPPER.js')['validateEnvironment']
  const validatePluginConfig: typeof import('./src/utils/PLUGINS__VITE--UNIFIED.js')['validatePluginConfig']
  const wrapperEnv: typeof import('./src/utils/ENV-PROCESSOR__VITE--WRAPPER.js')['wrapperEnv']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { GlobalErrorHandler } from './src/utils/ERROR-HANDLER__GLOBAL--SYSTEM.js'
  import('./src/utils/ERROR-HANDLER__GLOBAL--SYSTEM.js')
}
