/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    'COMPONENT__ERRORBOUNDARY-GLOBAL': typeof import('./src/components/COMPONENT__ERROR-BOUNDARY--GLOBAL.vue')['default']
    'COMPONENT__NAVIGATION-PRIMARY': typeof import('./src/components/COMPONENT__NAVIGATION--PRIMARY.vue')['default']
    'COMPONENT__NOTIFICATION-CONTAINER': typeof import('./src/components/COMPONENT__NOTIFICATION--CONTAINER.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    'PAGE__ABOUT-DEFAULT': typeof import('./src/views/PAGE__ABOUT--DEFAULT.vue')['default']
    'PAGE__BLOG-DETAIL': typeof import('./src/views/PAGE__BLOG--DETAIL.vue')['default']
    'PAGE__BLOG-LIST': typeof import('./src/views/PAGE__BLOG--LIST.vue')['default']
    'PAGE__CERTIFICATIONS-DEFAULT': typeof import('./src/views/PAGE__CERTIFICATIONS--DEFAULT.vue')['default']
    'PAGE__CONTACT-DEFAULT': typeof import('./src/views/PAGE__CONTACT--DEFAULT.vue')['default']
    'PAGE__HOME-DEFAULT': typeof import('./src/views/PAGE__HOME--DEFAULT.vue')['default']
    'PAGE__INDUSTRIES-DEFAULT': typeof import('./src/views/PAGE__INDUSTRIES--DEFAULT.vue')['default']
    'PAGE__LANDING-UNDERCONSTRUCTION': typeof import('./src/views/PAGE__LANDING--UNDER-CONSTRUCTION.vue')['default']
    'PAGE__NOTFOUND-404': typeof import('./src/views/PAGE__NOT-FOUND--404.vue')['default']
    'PAGE__PRODUCTS-DEFAULT': typeof import('./src/views/PAGE__PRODUCTS--DEFAULT.vue')['default']
    'PAGE__SERVICES-DEFAULT': typeof import('./src/views/PAGE__SERVICES--DEFAULT.vue')['default']
    'PAGE__SERVICESIMPORTDISTRIBUTION-DEFAULT': typeof import('./src/views/PAGE__SERVICES-IMPORT-DISTRIBUTION--DEFAULT.vue')['default']
    'PAGE__SERVICESOEM-DEFAULT': typeof import('./src/views/PAGE__SERVICES-OEM--DEFAULT.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
