/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    'COMPONENT__ERRORBOUNDARY-GLOBAL': typeof import('./src/components/COMPONENT__ERROR-BOUNDARY--GLOBAL.vue')['default']
    'COMPONENT__NOTIFICATION-CONTAINER': typeof import('./src/components/COMPONENT__NOTIFICATION--CONTAINER.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    'PAGE__HOME-DEFAULT': typeof import('./src/views/PAGE__HOME--DEFAULT.vue')['default']
    'PAGE__LANDING-UNDERCONSTRUCTION': typeof import('./src/views/PAGE__LANDING--UNDER-CONSTRUCTION.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
