/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    'COMPONENT__CONTACT-INFO': typeof import('./src/components/COMPONENT__CONTACT--INFO.vue')['default']
    'COMPONENT__CONTENT-SECTION': typeof import('./src/components/COMPONENT__CONTENT--SECTION.vue')['default']
    'COMPONENT__ERROR-STATE': typeof import('./src/components/COMPONENT__ERROR--STATE.vue')['default']
    'COMPONENT__ERRORBOUNDARY-GLOBAL': typeof import('./src/components/COMPONENT__ERROR-BOUNDARY--GLOBAL.vue')['default']
    'COMPONENT__FEATURE-LIST': typeof import('./src/components/COMPONENT__FEATURE--LIST.vue')['default']
    'COMPONENT__FEATURES-LIST': typeof import('./src/components/COMPONENT__FEATURES--LIST.vue')['default']
    'COMPONENT__FOOTER-SITE': typeof import('./src/components/COMPONENT__FOOTER--SITE.vue')['default']
    'COMPONENT__HEADER-SITE': typeof import('./src/components/COMPONENT__HEADER--SITE.vue')['default']
    'COMPONENT__HERO-PAGE': typeof import('./src/components/COMPONENT__HERO--PAGE.vue')['default']
    'COMPONENT__LOADING-STATE': typeof import('./src/components/COMPONENT__LOADING--STATE.vue')['default']
    'COMPONENT__NAVIGATION-PRIMARY': typeof import('./src/components/COMPONENT__NAVIGATION--PRIMARY.vue')['default']
    'COMPONENT__NOTIFICATION-CONTAINER': typeof import('./src/components/COMPONENT__NOTIFICATION--CONTAINER.vue')['default']
    'COMPONENT__PRODUCT-CARD': typeof import('./src/components/COMPONENT__PRODUCT--CARD.vue')['default']
    'COMPONENT__SERVICE-CARD': typeof import('./src/components/COMPONENT__SERVICE--CARD.vue')['default']
    'COMPONENT__SOCIAL-LINKS': typeof import('./src/components/COMPONENT__SOCIAL--LINKS.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    'PAGE__ABOUT-DEFAULT': typeof import('./src/views/PAGE__ABOUT--DEFAULT.vue')['default']
    'PAGE__BLOG-DETAIL': typeof import('./src/views/PAGE__BLOG--DETAIL.vue')['default']
    'PAGE__BLOG-LIST': typeof import('./src/views/PAGE__BLOG--LIST.vue')['default']
    'PAGE__CERTIFICATIONS-DEFAULT': typeof import('./src/views/PAGE__CERTIFICATIONS--DEFAULT.vue')['default']
    'PAGE__CONTACT-DEFAULT': typeof import('./src/views/PAGE__CONTACT--DEFAULT.vue')['default']
    'PAGE__CONTENT-DEMO': typeof import('./src/views/PAGE__CONTENT--DEMO.vue')['default']
    'PAGE__FEATURE-DEMO': typeof import('./src/views/PAGE__FEATURE--DEMO.vue')['default']
    'PAGE__HOME-DEFAULT': typeof import('./src/views/PAGE__HOME--DEFAULT.vue')['default']
    'PAGE__INDUSTRIES-DEFAULT': typeof import('./src/views/PAGE__INDUSTRIES--DEFAULT.vue')['default']
    'PAGE__LANDING-UNDERCONSTRUCTION': typeof import('./src/views/PAGE__LANDING--UNDER-CONSTRUCTION.vue')['default']
    'PAGE__NOTFOUND-404': typeof import('./src/views/PAGE__NOT-FOUND--404.vue')['default']
    'PAGE__PRODUCT-DEMO': typeof import('./src/views/PAGE__PRODUCT--DEMO.vue')['default']
    'PAGE__PRODUCTS-DEFAULT': typeof import('./src/views/PAGE__PRODUCTS--DEFAULT.vue')['default']
    'PAGE__SERVICE-DEMO': typeof import('./src/views/PAGE__SERVICE--DEMO.vue')['default']
    'PAGE__SERVICES-DEFAULT': typeof import('./src/views/PAGE__SERVICES--DEFAULT.vue')['default']
    'PAGE__SERVICESIMPORTDISTRIBUTION-DEFAULT': typeof import('./src/views/PAGE__SERVICES-IMPORT-DISTRIBUTION--DEFAULT.vue')['default']
    'PAGE__SERVICESOEM-DEFAULT': typeof import('./src/views/PAGE__SERVICES-OEM--DEFAULT.vue')['default']
    'PAGE__SOCIAL-DEMO': typeof import('./src/views/PAGE__SOCIAL--DEMO.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
